name = "roundliving-com"
compatibility_date = "2025-05-15"
pages_build_output_dir = "dist"

[[d1_databases]]
binding = "DB"
database_name = "roundliving-content"
database_id = "4e969778-5fde-4c53-aab2-9dfef9d878a6"
